export const CLIENT_ACHIEVEMENTS = [
  { id: 'first_quiz', icon: '🌟', label: 'Quiz Expert', description: 'Complete your first quiz' },
  { id: 'streak_3', icon: '🌤️', label: 'Getting Warm', description: 'Reach a 3-day streak' },
  { id: 'streak_7', icon: '🔥', label: 'Week Warrior', description: 'Reach a 7-day streak' },
  { id: 'streak_14', icon: '🔥', label: 'Fortnight Flame', description: 'Reach a 14-day streak' },
  { id: 'streak_30', icon: '🏆', label: 'Month Master', description: 'Reach a 30-day streak' },
  { id: 'correct_10', icon: '🌱', label: 'First Ten', description: 'Answer 10 words correctly' },
  { id: 'correct_50', icon: '🥉', label: 'Word Master', description: 'Answer 50 words correctly' },
  { id: 'correct_150', icon: '💎', label: 'Crystal Collector', description: 'Answer 150 words correctly' },
  { id: 'correct_300', icon: '🐉', label: 'Dragon Scholar', description: 'Answer 300 words correctly' },
  { id: 'correct_500', icon: '👑', label: 'Vocab Legend', description: 'Answer 500 words correctly' },
  { id: 'healthy_5', icon: '🌿', label: 'Sprout Guard', description: 'Keep 5 words healthy' },
  { id: 'healthy_20', icon: '🌌', label: 'Space Explorer', description: 'Keep 20 words healthy' },
  { id: 'healthy_50', icon: '💠', label: 'Crystal Keeper', description: 'Keep 50 words healthy' },
  { id: 'healthy_100', icon: '💚', label: 'Health Hero', description: 'Keep 100 words healthy' },
  { id: 'map_space', icon: '🚀', label: 'Lift Off', description: 'Unlock Space Station' },
  { id: 'map_crystal', icon: '⛏️', label: 'Cave Crawler', description: 'Unlock Crystal Caves' },
  { id: 'map_dragon', icon: '🐲', label: 'Dragon Rider', description: 'Unlock Dragon Ridge' },
  { id: 'perfect_quiz', icon: '✨', label: 'Flawless Explorer', description: 'Get every answer right in one Explorer quiz' },
  { id: 'perfect_3', icon: '🎯', label: 'Triple Perfect', description: 'Complete 3 perfect Explorer quizzes' },
  { id: 'comeback_kid', icon: '💪', label: 'Comeback Kid', description: 'Bring an At risk word back to Healthy' },
  { id: 'speed_runner', icon: '⚡', label: 'Speed Runner', description: 'Finish a Speed Match game' },
  { id: 'speed_perfect', icon: '💨', label: 'Lightning Match', description: 'Finish a Speed Match with no mistakes' },
  { id: 'speed_3', icon: '🏁', label: 'Triple Dash', description: 'Finish 3 Speed Match games' },
  { id: 'daily_goal', icon: '✅', label: 'Goal Getter', description: 'Reach your daily word goal' },
  { id: 'daily_goal_7', icon: '📅', label: 'Goal Streak', description: 'Reach your daily goal 7 days in a row' },
  { id: 'quest_first', icon: '📜', label: 'Quest Starter', description: 'Claim your first daily quest reward' },
  { id: 'quest_bonus', icon: '🏅', label: 'Daily Champion', description: 'Claim the all-quests bonus in one day' },
  { id: 'gems_100', icon: '💎', label: 'Gem Gatherer', description: 'Earn 100 gems' },
  { id: 'gems_500', icon: '💰', label: 'Treasure Hunter', description: 'Earn 500 gems' },
  { id: 'gift_first', icon: '🎁', label: 'Wish Granted', description: 'Redeem your first gift' },
] as const
